// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  OPENAI_API_KEY: string;
  APP_ENV: string;
  ASSETS: Fetcher;
  IMAGES_BUCKET: R2Bucket;
}